FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY . /app

ENV PYTHONUNBUFFERED=1
ENV API_BASE_URL=http://127.0.0.1:8080

EXPOSE 8501

CMD ["python", "-m", "streamlit", "run", "product_app.py", "--server.address=0.0.0.0", "--server.port=8501"]
